on: [push, pull_request]

name: Examples RP235x build

jobs:
  check_format_build:
    name: Examples - Check, Format, Build
    runs-on: ubuntu-latest
    steps:
      #Checkout source
      - name: Checkout sources
        uses: actions/checkout@v3
      #toolchain and tools
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: thumbv8m.main-none-eabihf
          components: rustfmt, clippy
      #build and lint
      - name: Run cargo check - examples rp235x
        working-directory: ./examples/rp235x/
        run: cargo check
      - name: Run cargo fmt - examples rp235x
        working-directory: ./examples/rp235x/
        run: cargo fmt --all -- --check
      - name: Run cargo clippy - examples rp235x
        working-directory: ./examples/rp235x/
        run: cargo clippy -- -D warnings
      - name: Run cargo build - examples rp235x
        working-directory: ./examples/rp235x/
        run: cargo build
